In [1]:
print('hello')

hello


In [2]:
#creating a dataframe

In [77]:
import pandas as pd
import numpy as np


In [63]:
data = {
    'Customer Id': [22051095,22051096,22051097,22051098,np.nan],
    'Age':[21,22,21,22,np.nan],
    'Gender':['Male','Female','Female',np.nan,np.nan],
    'Income':[10000,np.nan,30000,40000,np.nan],
    'City':['Urban','Rural','Urban',np.nan,np.nan],
    'Subscription Status':['Subscribed','Not Subscribed','Subscribed','Not Subscribed',np.nan]
    }

In [64]:
df=pd.DataFrame(data)

In [66]:
print("checking the missing values")
print(df.isna())

checking the missing values
   Customer Id    Age  Gender  Income   City  Subscription Status
0        False  False   False   False  False                False
1        False  False   False    True  False                False
2        False  False   False   False  False                False
3        False  False    True   False   True                False
4         True   True    True    True   True                 True


In [67]:
df

Customer Id   Age  Gender   Income   City Subscription Status
0   22051095.0  21.0    Male  10000.0  Urban          Subscribed
1   22051096.0  22.0  Female      NaN  Rural      Not Subscribed
2   22051097.0  21.0  Female  30000.0  Urban          Subscribed
3   22051098.0  22.0     NaN  40000.0    NaN      Not Subscribed
4          NaN   NaN     NaN      NaN    NaN                 NaN

In [68]:
print("filling the missing values")
df_filled = df.fillna(value={'Income': 20000, 'City': 'Urban', 'Gender': 'Female'}) 
df_filled

filling the missing values


Customer Id   Age  Gender   Income   City Subscription Status
0   22051095.0  21.0    Male  10000.0  Urban          Subscribed
1   22051096.0  22.0  Female  20000.0  Rural      Not Subscribed
2   22051097.0  21.0  Female  30000.0  Urban          Subscribed
3   22051098.0  22.0  Female  40000.0  Urban      Not Subscribed
4          NaN   NaN  Female  20000.0  Urban                 NaN

In [69]:
print('using dropna')

using dropna


In [70]:
df_dropped=df.dropna()

In [71]:
df_dropped

Customer Id   Age  Gender   Income   City Subscription Status
0   22051095.0  21.0    Male  10000.0  Urban          Subscribed
2   22051097.0  21.0  Female  30000.0  Urban          Subscribed

In [99]:
print("using lable encoding")
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()


using lable encoding


In [76]:
df

Customer Id   Age  Gender   Income   City Subscription Status
0   22051095.0  21.0    Male  10000.0  Urban          Subscribed
1   22051096.0  22.0  Female      NaN  Rural      Not Subscribed
2   22051097.0  21.0  Female  30000.0  Urban          Subscribed
3   22051098.0  22.0     NaN  40000.0    NaN      Not Subscribed
4          NaN   NaN     NaN      NaN    NaN                 NaN

In [80]:
label_encoder = LabelEncoder()
columns_to_encode = ['Gender', 'City', 'Subscription Status']
# Apply label encoding 
for col in columns_to_encode:
    df[col] = label_encoder.fit_transform(df[col].fillna('Unknown')) 

print(df)


   Customer Id   Age  Gender   Income  City  Subscription Status
0   22051095.0  21.0       1  10000.0     2                    1
1   22051096.0  22.0       0      NaN     0                    0
2   22051097.0  21.0       0  30000.0     2                    1
3   22051098.0  22.0       2  40000.0     1                    0
4          NaN   NaN       2      NaN     1                    2


In [92]:
print("using one hot encoding")
df_encoded = pd.get_dummies(df, dtype=int)
df_encoded

using one hot encoding


Customer Id   Age  Gender   Income  City  Subscription Status
0   22051095.0  21.0       1  10000.0     2                    1
1   22051096.0  22.0       0      NaN     0                    0
2   22051097.0  21.0       0  30000.0     2                    1
3   22051098.0  22.0       2  40000.0     1                    0
4          NaN   NaN       2      NaN     1                    2

In [98]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

print("using standard scaler")
scaler = StandardScaler()
model = scaler.fit(df_dropped)
scaled_data = model.transform(df_dropped)
print(scaled_data)

print("using minmaxscaler")
scaler1 = MinMaxScaler()
model=scaler1.fit(df_dropped)
scaled_data1=model.transform(df_dropped)
print(scaled_data1)


using standard scaler
[[-1.  0.  1. -1.  0.  0.]
 [ 1.  0. -1.  1.  0.  0.]]
using minmaxscaler
[[0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0.]]
